version: "3.8"
services:
  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - "5173:5173"
    networks: 
      - mern-docker-compose-network
    environment:
      REACT_APP_API_URL: http://backend:5050
    depends_on:
      - backend
    
  backend:
    container_name: backend
    build: ./backend
    ports:
      - "5050:5050"
    networks:
      - mern-docker-compose-network
    environment:
      MONGO_URI: mongodb://mongo:27017/mydb
    depends_on:
      - mongodb

  mongodb:
    container_name: mongodb
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - mern-docker-compose-network
    volumes:
      - mongodb-data:/data/db

networks:
  mern-docker-compose-network:
    driver: bridge 

volumes:
  mongodb-data:
    driver: local 
